### ISSUE TITLE
Energy monitoring through API

### ISSUE THREAD

**Issue by andylox** [codetheweb/tuyapi#121]
Will it be somehow possible to get the actual power data that was consumend by the socket through the API?

Its possible with the official App. Thanks

**Comment by codetheweb** [comment]
Yes, should be fairly easy.  Try the below script to get all the properties for your device:

```javascript
const TuyAPI = require('tuyapi');

const device = new TuyAPI({
  id: 'xxxxxxxxxxxxxxxxxxxx',
  key: 'xxxxxxxxxxxxxxxx',
  ip: 'xxx.xxx.xxx.xxx'});

device.get({schema: true}).then(data => {
  console.log(data);
});
```

Then, figure out which property contains the wattage drawn by comparing values with the app.

**Comment by andylox** [comment]
Thank you, this is the result:
`  dps:
   { '1': false,
     '9': 0,
     '18': 0,
     '19': 0,
     '20': 2333,
     '21': 1,
     '22': 665,
     '23': 33366,
     '24': 19190,
     '25': 1085 } }

The App shows me 680 watts, so I guess its dps 22, I will monitor it again in the future.`

**Comment by codetheweb** [comment]
Alright, glad you figured it out.

**Comment by andylox** [comment]
Hi, it seems the DPS 22 is changing every day, might be its only the power consumption by day and not in total. Any hint, might be it needs to be converted from any other unit then KWh?

**Comment by codetheweb** [comment]
The one device that I own that reports power consumption reports it in KWs, so I multiply by 1000 to get watts.  I would just continue poking around the app and the response to figure out what maps to what.

If you take a screenshot of the app with a load attached and then the schema like you did above, I may be able to help further.

**Comment by nalajcie** [comment]
Hi,
I've also have the plug with energy monitoring. When You use TuyaSmart android app, the DPS map can be obtained by reading `adb logcat`

This is the relevant part:
```
schema:
 { switch_1:
    { type: 'bool',
      name: '开关1',
      mode: 'rw',
      code: 'switch_1',
      id: '1',
      schemaType: 'bool',
      iconname: 'icon-dp_power2',
      dptype: 'obj' },
   countdown_1:
    { type: 'value',
      name: '开关1倒计时',
      mode: 'rw',
      code: 'countdown_1',
      id: '9',
      schemaType: 'value',
      iconname: 'icon-dp_time2',
      dptype: 'obj',
      max: 86400,
      min: 0,
      scale: 0,
      step: 1,
      unit: 's' },
   add_ele:
    { type: 'value',
      name: '增加电量',
      mode: 'rw',
      code: 'add_ele',
      id: '17',
      schemaType: 'value',
      iconname: 'icon-battery',
      dptype: 'obj',
      max: 50000,
      min: 0,
      scale: 3,
      step: 100,
      unit: '' },
   cur_current:
    { type: 'value',
      name: '当前电流',
      mode: 'ro',
      code: 'cur_current',
      id: '18',
      schemaType: 'value',
      iconname: 'icon-Ele',
      dptype: 'obj',
      max: 30000,
      min: 0,
      scale: 0,
      step: 1,
      unit: 'mA' },
   cur_power:
    { type: 'value',
      name: '当前功率',
      mode: 'ro',
      code: 'cur_power',
      id: '19',
      schemaType: 'value',
      iconname: 'icon-dp_tool',
      dptype: 'obj',
      max: 50000,
      min: 0,
      scale: 1,
      step: 1,
      unit: 'W' },
   cur_voltage:
    { type: 'value',
      name: '当前电压',
      mode: 'ro',
      code: 'cur_voltage',
      id: '20',
      schemaType: 'value',
      iconname: 'icon-a_function_turb
      dptype: 'obj',
      max: 5000,
      min: 0,
      scale: 1,
      step: 1,
      unit: 'V' },
   test_bit:
    { type: 'value',
      name: '产测结果位',
      mode: 'ro',
      code: 'test_bit',
      id: '21',
      schemaType: 'value',
      iconname: 'icon-dp_direction',
      dptype: 'obj',
      max: 5,
      min: 0,
      scale: 0,
      step: 1,
      unit: '' },
   voltage_coe:
    { type: 'value',
      name: '电压校准系数',
      mode: 'ro',
      code: 'voltage_coe',
      id: '22',
      schemaType: 'value',
      iconname: 'icon-gaodiyin',
      dptype: 'obj',
      max: 1000000,
      min: 0,
      scale: 0,
      step: 1,
      unit: '' },
   electric_coe:
    { type: 'value',
      name: '电流校准系数',
      mode: 'ro',
      code: 'electric_coe',
      id: '23',
      schemaType: 'value',
      iconname: 'icon-gaodiyin',
      dptype: 'obj',
      max: 1000000,
      min: 0,
      scale: 0,
      step: 1,
      unit: '' },
   power_coe:
    { type: 'value',
      name: '功率校准系数',
      mode: 'ro',
      code: 'power_coe',
      id: '24',
      schemaType: 'value',
      iconname: 'icon-gaodiyin',
      dptype: 'obj',
      max: 1000000,
      min: 0,
      scale: 0,
      step: 1,
      unit: '' },
   electricity_coe:
    { type: 'value',
      name: '电量校准系数',
      mode: 'ro',
      code: 'electricity_coe',
      id: '25',
      schemaType: 'value',
      iconname: 'icon-gaodiyin',
      dptype: 'obj',
    }
}
```

So the interesting DPS are:
```
[ 1] switch_1       // on/off
[ 9] countdown_1    // value in secs, can be set
[18] cur_current    // in mA
[19] cur_power      // in W * 10
[20] cur_voltage    // in V * 10
```
Other DPS are read-only and do not change with time (probably some calibration form the factory).

I believe the cumulative energy (kWh) is a feature of cloud system (computed from voltage and current which device sends every 2s) and not the device itself.

**Comment by aleqx** [comment]
I have an energy monitoring plug as well and would like to read the current/voltage/power/energy ... but I also want to reset the counters.

How would I go resetting those counters? I have some experience with the TP-Link HS110 but not these devices.

@nalajcie how do you actually connect using adb to the device? Sorry if this is documented somewhere and I missed it.

**Comment by codetheweb** [comment]
What counters are you talking about @aleqx? AFAIK, the cloud/app increments data like total power drawn and not the device itself.

**Comment by aleqx** [comment]
I'm talking about the counters for energy (kWh), and values for current, voltage, power.

These must be stored in the device, since they are visible when there is no internet connection.

Unrelated or possibly related: my Tuya smartplugs are absolute shit in terms of power reporting. The reported power in Watts is totally inacurrate, very much off the value I get when multiplying the current by voltage (this is for purely resistive loads that draw, for example, 1500W ... the app is reporting 170W and at times 350W). The current value in mA seems to be more accurate. I can't trust the energy counter either if it's based on wrong instantaneous power measurement. I wanted to see if resetting the counters helps. I already tried factory defaults.

**Comment by aleqx** [comment]
> I found out that You can deregister and register again the same device - then the history values are forgotten.

That's not true, at least for my smart plugs (I tried it twice).

> I've managed to reverse-engineer the new sign mechanism (see: nalajcie/tuya-sign-hacking) and I'm working to implement it in the TuyaAPI/cloud npm package (my fork: nalajcie/cloud). It's not yet finished but I'm able to log in using TuyaSmart credentials and get the devices list with current values with a few lines of JS :). I'll create Pull request when I will be sure it's fully functional.

That's really cool, and I will definitely check it out. Many thanks for the work! Will that make it possible to control (and read off values from) these devices without an internet connection? I have some remote sites which don't have an internet connection where I'd like to use these. The TP-Link HS110 has been much more hacker friendly so far ... but also 3x the price and much bulkier in size,

**Comment by codetheweb** [comment]
>  I'll create Pull request when I will be sure it's fully functional.

Cool, I'm looking forward to it @nalajcie.

**Comment by nalajcie** [comment]
> > I found out that You can deregister and register again the same device - then the history values are forgotten.
> 
> That's not true, at least for my smart plugs (I tried it twice).

Thanks for the info, I did it only once and tried a few other things at the same time using the Cloud API, which might have triggered the deletion of the device history.

> That's really cool, and I will definitely check it out. Many thanks for the work! Will that make it possible to control (and read off values from) these devices without an internet connection? I have some remote sites which don't have an internet connection where I'd like to use these. The TP-Link HS110 has been much more hacker friendly so far ... but also 3x the price and much bulkier in size,

No, this is the *cloud* API - it gives You control over Your device (state and data) from anywhere via Tuya servers. Also - as the total energy is only computed on the server - if there is no internet connectivity, no energy will be computed (Yes, I know that You can see the total energy increase on Your phone if You're in the same WiFi and disconnected from the internet - but it works only because TuyaSmart app captures MQTT messages sent from the device every 2s and computes the same energy in the app (which is actually quite smart - You see the values changing instantly and the servers are not overloaded with requests)).

If You would like to use the outlets without any cloud service I would recommend changing the firmware (I think Tasmota supports many Tuya-branded plugs) and re-calibrating the power measurement coefficients (each device has to be calibrated in the factory due to some variance in discrete components used in measurement circuit). I haven't done it myself but from what I've read You should be able to do it without disassembling the plug (see: https://github.com/arendst/Sonoff-Tasmota/wiki/Tuya-OTA).
