### ISSUE TITLE
Infinite loop in TuyaDevice.prototype._extractJSON function

### ISSUE THREAD

**Issue by bobalob** [codetheweb/tuyapi#18]
If the message contains more open braces "{" than close braces "}" the function goes into an infinite loop.

The real fix would be to clean up the decrypted message to remove the invalid brace at the end. I have seen similar characters at the end of messages when using zero padding in AES (not 100% sure this is the issue.) I cleaned up my messages by switching to PKCS7 padding.

A quick fix is to check for the number of close braces before entering the loop

```
    var leftBrackets = stringOccurrence(data, '{');
    var rightBrackets = stringOccurrence(data, '}');
    if (leftBrackets > rightBrackets) { leftBrackets = rightBrackets }
```

but this could end up with bad returned JSON if there happens to be other invalid '{' and '}' characters

**Comment by codetheweb** [comment]
Yeah, I'm not completely sure what the best solution is here.  There's three possibilities:
- Formatting is perfect, none of the padding renders as an ASCII character and `numOfLeftBrackets == numOfRightBrackets`
- Random padding results in `numOfLeftBrackets > numOfRightBrackets`
- Random padding results in `numOfRightBrackets > numOfLeftBrackets`

I'm not really sure what to do.  One interesting thing to note is that I've never seen a `}` *before* the main payload, although that's most likely due to chance and not design.

The best way to parse returned data would be to simply start parsing at a certain index in the string like the actual device does, however this would add complexity as we would need to add the index to `requests.json`.

**Comment by bobalob** [comment]
Is the message returned from the device encrypted or plain text?

**Comment by codetheweb** [comment]
The majority of the time it is returned in plain text.  However, there seem to be a (very) few random times when it's returned encrypted.  I have no idea what triggers this.  If it's returned encrypted, a JSON error will be thrown.

**Comment by codetheweb** [comment]
Fixed.
