### ISSUE TITLE
Key is missing or incorrect

### ISSUE THREAD

**Issue by undjike** [codetheweb/tuyapi#392]
I'm not able to make this package work. I've installed it throught npm and set the id (ACCESS ID from Tuya) and KEY (ACCESS SECRET). Maybe is not the good correspondance.

 - OS: Windows 10
 - Node Version: v14.15.1

**Comment by codetheweb** [comment]
Can you please provide more details? What isn't working?

**Comment by codetheweb** [comment]
I think you may have mixed up the cloud API credentials with the local device credentials.

**Comment by undjike** [comment]
> Can you please provide more details? What isn't working?

I got the credentials by creating a project on the Tuya web platform.

I thought I had to provide them when instanciating the TuyaApi class to access all my devices. Is it not the case ?

**Comment by undjike** [comment]
![Screenshot_20201222-100649_GitHub.jpg](https://user-images.githubusercontent.com/57102409/102870556-74e83180-443d-11eb-96aa-8e8517991e27.jpg)

This is the code I want to test. 
I only filled in my credentials and logged the response.

**Comment by undjike** [comment]
I always receive an error output `Key is missing or incorrect`.

**Comment by codetheweb** [comment]
It sounds like you didn't completely follow [the instructions](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md). After obtaining the API keys on Tuya's website, you have to use `tuya-cli` to list out the IDs and keys of your devices.

**Comment by corey-mitchell** [comment]
> I got the credentials by creating a project on the Tuya web platform.
> 
> I thought I had to provide them when instanciating the TuyaApi class to access all my devices. Is it not the case ?

No, it is not. As he said, the credentials you pass here are the credentials of the local device itself. 

> I think you may have mixed up the cloud API credentials with the local device credentials.

Like me, you mistook the two. But it's a bit more clear if you think about the fact that each instance of the class should be for a unique device, not a unique user.

You needed that cloud API key to link the device so that you could get the ID and Key of the local device(s). You then use those local device ID(s) and Key(s) to pass to the class instance.

Quite a bit late, but hopefully it helps someone down the line.
