### ISSUE TITLE
No "Smart Home Devices Management in Service API

### ISSUE THREAD

**Issue by richibrics** [codetheweb/tuyapi#537]
Hi
I followed all the steps to create a new project and subscribe to "Smart Home Devices Management"but I can't find it in the list of available services. I also searched, I "Device Connection Service" but I could not find anything.

Is it possible that Tuya IOT renamed the API service ?

**Comment by lionhe1966** [comment]
It appears that now the APIs have been reorganized and IOT core is the service to subscribe

**Comment by bobloadmire** [comment]
I subscribed to IoT core but when I query my device ID, it still returns "access denied" and doesn't grab the local keys.

**Comment by cconde** [comment]
+1

**Comment by rsnel** [comment]
I accepted the 'default APIs' in the screen  (accept service options instead of skip), i got:


IoT Core 
Authorization
Smart Home Scene Linkage
IoT Data Analytics

This happens in step 2 of "Linking a Tuya device with Smart Link" (of course I selected the wrong datacenter, so I had to redo the project). I didn't do step 3. And then went to "Listing Tuya devices from the Tuya Smart or Smart Life apps"

The 'virtual ID' (needed by "tuya-cli wizard") can be found in the device 'info' screen, it is a hex string with some non-hex letters at the end.

**Comment by ALaSDos** [comment]
The IoT Core also works for me.
But the trial version is just for 30 days?
After the trial period, it is supposed to cost 5,000 USD per year?

**Comment by rsnel** [comment]
You only need the IoT Core service to get the keys. Afterwards you can revoke the api, and (for my usecase: localtuya) stuff will keep working.

**Comment by otherguy** [comment]
@rsnel of course I also selected the wrong data center. But you can actually edit your project and select a new datacenter location (or even additional ones). No need to recreate the project!

**Comment by UsefulVid** [comment]
> I got it to work!
> 
> I accepted the 'default APIs' in the screen (accept service options instead of skip), i got:
> 
> IoT Core Authorization Smart Home Scene Linkage IoT Data Analytics
> 
> This happens in step 2 of "Linking a Tuya device with Smart Link" (of course I selected the wrong datacenter, so I had to redo the project). I didn't do step 3. And then went to "Listing Tuya devices from the Tuya Smart or Smart Life apps"
> 
> The 'virtual ID' (needed by "tuya-cli wizard") can be found in the device 'info' screen, it is a hex string with some non-hex letters at the end.

https://github.com/codetheweb/tuyapi/pull/553
