### ISSUE TITLE
Can't complete Link Tuya App Account

### ISSUE THREAD

**Issue by kxkayser** [codetheweb/tuyapi#573]
Hi.  Following the steps in "Listing Tuya devices from the Tuya Smart or Smart Life apps".  When I scan the QR code in the Smartlife App, the confirmation is successful and the "Link Tuya App Account" pops up on the Tuya site.  I select the Automatic Link and Read, write and Manage options and click OK.  Then 2 quick pop-up lines appear near he top of the browser window that say "x - capp_binded_userid".  They disappear and I am still in the link screen.  See attached.  No devices are discovered or added to the project
![Tuya](https://user-images.githubusercontent.com/46426583/160922504-8427ceb0-497e-465d-959b-baad17726a55.JPG)

.

**Comment by PanicMan** [comment]
Have the same problem, didn't managed to fix it yet, tried to clear the cache for the app, changed password, as it was mentioned somewhere else... Nothing works... Any ideas how to get the device ID's w/o that stupid API?

**Comment by kxkayser** [comment]
I opened a ticket with Tuya and they responded next day.  They suggested I change my Data Center to Western USA even though I am in NC.  That solved the problem and I was able to link my account.  Now back to mqtt

**Comment by nzf4de** [comment]
Thanks kxkayser, changing the datacenter to western usa fixed it for me as well. Been trying to get it connecting for over a month to smart home.

**Comment by kxkayser** [comment]
Glad it worked for you too. I was able to integrate my Tuya devices with my other devices on the same Node-Red dashboard. Just what I wanted.

**Comment by jsessink** [comment]
Ran into the same issue today.  Glad I found this, since it worked for me as well!

**Comment by craigcurtin-dev** [comment]
Ran into the same issue as well - went through a whole heap of troubleshooting - turns out you need access to the magic table the lists each of the data centres - here is a link to it.

https://github.com/tuya/tuya-home-assistant/blob/d7fa8a4d0098f3611755d05ebfbd1904036c6b9d/docs/regions_dataCenters.md

Once i entered Central Europe (makes sense for Australia - NOT) all went OK

Craig

**Comment by michelefa1988** [comment]
For me the problem was solved by

1) Enabling all data centers in the projects
2) Authorised IoT core trial  (very important step - see screenshot )
3) The datacenter is probably a little random so I tried them all, until central Europe worked

![image](https://user-images.githubusercontent.com/12183072/173549935-47d2b2d6-baab-4b8c-8e96-63b3fc17898c.png)
